name: Code checks
 
on: 
  push: 
    branches: [ main, develop ] 
  pull_request: 
    branches: [ main, develop] 
    
  workflow_dispatch: 
 
jobs: 
  on_build_actions: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install dependencies 
        run: | 
          cd $GITHUB_WORKSPACE 
          python mintests2.py 
      - name: Run Tests 
        run: python -m unittest discover -v . "*_unittest.py"
