name: Code_checks
 
on: 
  push: 
    branches: [ main, develop ] 
  pull_request: 
    branches: [ main, develop ] 
    
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE 
      - name: demo
        if: ${{ always() }}
        run: python -m unittest mintests2
     
      - if: ${{success()}}
        name: send telegram message+
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             That's okey.
             ${{ github.actor }} created commit:
             Commit message: ${{ github.event.commits[0].message }}
            
             Repository: ${{ github.repository }}
            
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 
   
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR
             ${{ github.actor }} created commit:
             Commit message: ${{ github.event.commits[0].message }}
            
             Repository: ${{ github.repository }}
            
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 

  build-min: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: min
        if: ${{ always() }}
        run: python -m unittest mintest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in mintest        

  build-max: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: max
        if: ${{ always() }}
        run: python -m unittest maxtest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in maxtest 
  
  build-sum: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: sum
        if: ${{ always() }}
        run: python -m unittest sumtest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in sumtest     

  build-mult: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: mult
        if: ${{ always() }}
        run: python -m unittest multtest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in multtest     
   
  build-logic: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: logic
        if: ${{ always() }}
        run: python -m unittest logictest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in logictest 
    
  build-time: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE         
      - name: time
        if: ${{ always() }}
        run: python -m unittest timetest
        
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in timetest 
