name: Code_checks
 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
    
  workflow_dispatch: 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
      - name: Install deps
        run: | 
          cd $GITHUB_WORKSPACE 
      - name: demo
        if: ${{ always() }}
        run: python -m unittest mintests2
     
      - if: ${{success()}}
        name: send telegram message+
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             That's okey.
             ${{ github.actor }} created commit:
             Commit message: ${{ github.event.commits[0].message }}
            
             Repository: ${{ github.repository }}
            
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 
   
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR
             ${{ github.actor }} created commit:
             Commit message: ${{ github.event.commits[0].message }}
            
             Repository: ${{ github.repository }}
            
             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}} 
        
      - name: min
        if: ${{ always() }}
        run: python -m unittest mintest
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in mintest        
      
      - name: max
        if: ${{ always() }}
        run: python -m unittest maxtest
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in maxtest 
             
      - name: sum
        if: ${{ always() }}
        run: python -m unittest sumtest
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in sumtest     

      - name: mult
        if: ${{ always() }}
        run: python -m unittest multtest
      - if: ${{failure()}}
        name: send telegram message-
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
             ERROR in multtest     
   
